# The upstream UI build predates native PipeWire default-source and microphone-mute support.
# Patch only the copied assets: keep the upstream submodule clean and make packaging reproducible.
function(soundux_patch_frontend directory)
    file(GLOB bundles "${directory}/js/app.*.js")
    list(LENGTH bundles count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Expected one Soundux frontend app bundle, found ${count}")
    endif()
    list(GET bundles 0 bundle)
    file(READ "${bundle}" content)
    set(old_mutation "e.settings.audioBackend=t,t==g.PipeWire&&(e.settings.muteDuringPlayback=!1,e.settings.useAsDefaultDevice=!1)")
    set(old_disabled "disabled:1===e.$store.getters.settings.audioBackend,")
    string(FIND "${content}" "${old_mutation}" mutation_index)
    string(FIND "${content}" "${old_disabled}" disabled_index)
    if(mutation_index EQUAL -1 OR disabled_index EQUAL -1)
        message(FATAL_ERROR "Upstream UI changed; review the native PipeWire compatibility patch")
    endif()
    string(REPLACE "${old_mutation}" "e.settings.audioBackend=t" content "${content}")
    string(REPLACE "${old_disabled}" "" content "${content}")
    file(WRITE "${bundle}" "${content}")
endfunction()
